import {
  Controller,
  Get,
  Headers,
  HttpCode,
  HttpStatus,
  Inject,
  Param,
  Post,
  Req,
} from '@nestjs/common';
import {
  ApiBadRequestResponse,
  ApiCreatedResponse,
  ApiHeader,
  ApiNotFoundResponse,
  ApiOkResponse,
  ApiOperation,
  ApiParam,
  ApiServiceUnavailableResponse,
  ApiTags,
} from '@nestjs/swagger';
import { apiErrorResponse, ApiSessionAuth } from '../common/decorators/api-session-auth.decorator';
import { CurrentUser } from '../common/decorators/current-user.decorator';
import { Public } from '../common/decorators/public.decorator';
import {
  AuthenticatedRequest,
  AuthenticatedUser,
} from '../common/interfaces/authenticated-request';
import {
  CheckoutSessionResponseDto,
  CheckoutStatusResponseDto,
  WebhookReceivedResponseDto,
} from './dto/payment-response.dto';
import { PaymentsService } from './payments.service';

@ApiTags('payments')
@Controller('payments')
export class PaymentsController {
  constructor(@Inject(PaymentsService) private readonly paymentsService: PaymentsService) {}

  @ApiSessionAuth()
  @Post('checkout')
  @ApiOperation({ summary: 'Reprice the cart and create a Stripe Checkout Session' })
  @ApiCreatedResponse({ type: CheckoutSessionResponseDto })
  @ApiBadRequestResponse(
    apiErrorResponse('The cart is empty, contains inactive products, or exceeds monetary limits'),
  )
  @ApiServiceUnavailableResponse(apiErrorResponse('Stripe is not configured or unavailable'))
  checkout(@CurrentUser() user: AuthenticatedUser) {
    return this.paymentsService.createCheckout(user.id);
  }

  @ApiSessionAuth()
  @Get('checkout/:sessionId/status')
  @ApiOperation({ summary: 'Get the authenticated customer checkout status' })
  @ApiParam({ name: 'sessionId', example: 'cs_test_a1b2c3' })
  @ApiOkResponse({ type: CheckoutStatusResponseDto })
  @ApiBadRequestResponse(apiErrorResponse('The Stripe checkout session ID is invalid'))
  @ApiNotFoundResponse(
    apiErrorResponse('The checkout does not belong to this user or was not found'),
  )
  checkoutStatus(@CurrentUser() user: AuthenticatedUser, @Param('sessionId') sessionId: string) {
    return this.paymentsService.getCheckoutStatus(user.id, sessionId);
  }

  @Public()
  @HttpCode(HttpStatus.OK)
  @Post('webhook')
  @ApiOperation({ summary: 'Receive signed Stripe webhook events' })
  @ApiHeader({
    name: 'stripe-signature',
    required: true,
    description: 'Signature generated by Stripe for the unmodified request body',
  })
  @ApiOkResponse({ type: WebhookReceivedResponseDto })
  @ApiBadRequestResponse(
    apiErrorResponse('The signature, event mode, payment data, amount, or currency is invalid'),
  )
  @ApiNotFoundResponse(apiErrorResponse('The referenced checkout session was not found'))
  @ApiServiceUnavailableResponse(apiErrorResponse('The Stripe webhook secret is not configured'))
  webhook(@Req() request: AuthenticatedRequest, @Headers('stripe-signature') signature?: string) {
    if (!request.rawBody) {
      throw new Error('Raw request body is unavailable; rawBody must be enabled at bootstrap');
    }
    return this.paymentsService.handleWebhook(request.rawBody, signature);
  }
}
